name: ptixiaki_sleep_stages #όνομα εφαρμογής
description: A new Flutter project. #συνοπτική περιγραφή
publish_to: "none" #δεν θέλουμε να γίνει publish

version: 1.0.0+1
environment:
  sdk: ">=2.17.0-105.0.dev <3.0.0"

dependencies: #βιβλιοθήκες εφαρμογής
  flutter:
    sdk: flutter
  animations: ^2.0.2 #βιβλιοθήκη για την υποστήριξη animations
  intl: ^0.17.0 #βιβλιοθήκη για να είναι δυνατό το format των ημερομηνιών
  font_awesome_flutter: ^10.1.0 #fonts
  flutter_rating_bar: ^4.0.0 #rating bar widget
  date_picker_timeline: ^1.2.3 #για το ημερολόγιο
  fl_chart: ^0.50.1 #βιβλιοθήκη γραφημάτων
  syncfusion_flutter_gauges: ^20.1.47 #gauges charts
  syncfusion_flutter_charts: ^20.1.50 #βιβλιοθήκη γραφημάτων
  percent_indicator: ^3.4.0
  sqflite: ^2.0.2 #βάση εφαρμογής
  path: ^1.8.1 #για την εύρεση του path της συσκευής
  provider: ^6.0.2 #state management library
  google_nav_bar: ^5.0.6 #έτοιμο κάτω μενού πλοήγησης απο την google

  cupertino_icons: ^1.0.2 #για την χρήση των στοιχείων διεπαφής που προσφέρει το flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sleep_app/ #δηλώνουμε τον φάκελο μέσα στο οποίο υπάρχουν οι εικόνες
